define and export TMPDIR="$HOME/tmp" create $TMPDIR inside chroot print_uris: enhanced error diagnostics

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -188,11 +188,30 @@ print_uris()
 	[ -n "$APT_CONFIG" ] || Fatal "APT_CONFIG undefined."
 	local out
 	if ! out="$(apt-get -q -y --print-uris install "$@" 2>&1)"; then
-		echo -E "$out" >&2
+		printf %s "$out" >&2
 		Fatal "failed to calculate package file list."
 	fi
-	echo -E "$out" |sed -ne "s/^'\\(file\\|copy\\):\\([^']\\+\\)' .*/\\2/pg" || return 1
-	Verbose "calculated package file list."
+
+	local pattern0="'\\([a-z]\\+\\):\\([^']\\+\\)' .*"
+	local pattern1="'\\(file\\|copy\\):\\([^']\\+\\)' .*"
+
+	local all_uris
+	if ! all_uris="$(printf %s "$out" |sed -ne "s/^$pattern0/&/pg")"; then
+		printf %s "$out" >&2
+		Fatal "failed to filter package file list."
+	fi
+	local uris
+	if ! uris="$(printf %s "$all_uris" |sed -ne "s/^$pattern1/\\2/pg")"; then
+		printf %s "$out" >&2
+		Fatal "failed to filter package file list."
+	fi
+
+	if [ "$all_uris" != "$uris" ]; then
+		printf %s "$out" >&2
+		Fatal "calculated package file list is not local."
+	fi
+	printf %s "$uris" &&
+		Verbose "calculated package file list."
 }
 
 # quote argument for /.host/entry.
@@ -204,6 +223,8 @@ quote_arg()
 }
 
 entry_header='#!/bin/sh -e
+TMPDIR="$HOME/tmp"
+export TMPDIR
 cd /.in'
 
 entry_fakeroot_header='#!/bin/sh -e
