install_exit_handler(): New function

diff --git a/functions.in b/functions.in
--- a/functions.in
+++ b/functions.in
@@ -384,6 +384,37 @@ __EOF__
 	chmod 755 "$entry"
 }
 
+hasher_exit_handler()
+{
+	local rc=$?
+	trap - EXIT
+	rm -rf -- "$workdir/lockdir"
+	exit $rc
+}
+
+install_exit_handler()
+{
+	local lockdir="$workdir/lockdir"
+	local pidfile="$lockdir/pid"
+	if ! mkdir -m700 $verbose -- "$lockdir"; then
+		if [ -s "$pidfile" ]; then
+			local pid
+			pid="$(head -c32 "$pidfile")"
+			if kill -0 -- "$pid" 2>/dev/null; then
+				Info "Working directory \`$workdir' is locked, pid=$pid."
+				ps hp "$pidfile" 2>/dev/null
+			else
+				Info "Working directory \`$workdir' is locked, stale pid=$pid."
+			fi
+		fi
+		Fatal 'Unable to create lock directory.'
+	fi
+
+	trap hasher_exit_handler HUP PIPE INT QUIT TERM EXIT
+
+	echo $$ >"$pidfile"
+}
+
 # assumed: defined APT_CONFIG, prog_apt_get
 print_uris()
 {
