Replace Info()/Fatal()/Verbose() with message()/fatal()/verbose() from libshell

diff --git a/hasher/hsh b/hasher/hsh
--- a/hasher/hsh
+++ b/hasher/hsh
@@ -151,7 +151,7 @@ while :; do
 		--number)
 			if [ -z "${2##/*}" ]; then
 				[ -d "$2" ] ||
-					Fatal "$1: $2: Directory not available."
+					fatal "$1: $2: Directory not available."
 				number="$2"
 			else
 				number="$(opt_check_number "$1" "$2")"
@@ -184,7 +184,7 @@ while :; do
 			;;
 		--target) shift; target="$1"
 			[ -z "${target##[A-Za-z]*}" ] ||
-				Fatal "--target: $target: invalid architecture."
+				fatal "--target: $target: invalid architecture."
 			;;
 		--wait-lock) lock_nowait=
 			;;
@@ -199,7 +199,7 @@ while :; do
 			shift
 			;;
 		--contents-index-*)
-			Info "Warning: obsolete option $1 ignored."
+			message "Warning: obsolete option $1 ignored."
 			shift
 			;;
 		--) shift; break
@@ -230,7 +230,7 @@ if [ -z "$initroot_only" -a -z "$cleanup_only" ]; then
 		[ "$#" -ge 1 ] || show_usage 'Insufficient arguments.'
 	fi
 
-	[ -e "$1" ] || Fatal "$1: no such file or directory."
+	[ -e "$1" ] || fatal "$1: no such file or directory."
 
 	if [ -z "$workdir" -o -d "${1:-}" ]; then
 		set_workdir "${1:-}"
@@ -262,31 +262,31 @@ fi
 for f in "$@"; do
 	[ -z "${f##/*}" ] || f="$saved_cwd/$f"
 	[ -e "$f" ] ||
-		Fatal "$f: file not found."
+		fatal "$f: file not found."
 	[ -f "$f" ] ||
-		Fatal "$f: not a regular file."
+		fatal "$f: not a regular file."
 	[ -r "$f" ] ||
-		Fatal "$f: cannot access source."
+		fatal "$f: cannot access source."
 	[ -s "$f" ] ||
-		Fatal "$f: empty source file."
+		fatal "$f: empty source file."
 done
 
 cleanup_workdir()
 {
 	if [ -d aptbox ]; then
 		rm -rf aptbox &&
-			Verbose 'Removed aptbox.' ||
-			Fatal 'Failed to remove aptbox.'
+			verbose 'Removed aptbox.' ||
+			fatal 'Failed to remove aptbox.'
 	fi
 	if [ -d cache ]; then
 		rm -rf cache &&
-			Verbose 'Removed cache.' ||
-			Fatal 'Failed to remove cache.'
+			verbose 'Removed cache.' ||
+			fatal 'Failed to remove cache.'
 	fi
 	if [ -d repo ]; then
 		rm -rf repo &&
-			Verbose 'Removed repo.' ||
-			Fatal 'Failed to remove repo.'
+			verbose 'Removed repo.' ||
+			fatal 'Failed to remove repo.'
 	fi
 	if [ -d chroot ]; then
 		deduce_lock_hasher_priv
@@ -296,8 +296,8 @@ cleanup_workdir()
 			${verbose:+$verbose} \
 			${number:+--number=$number} \
 			&& 
-			Verbose 'Removed chroot.' ||
-			Fatal 'Failed to remove chroot.'
+			verbose 'Removed chroot.' ||
+			fatal 'Failed to remove chroot.'
 	fi
 }
 
diff --git a/hasher/hsh-fakedev b/hasher/hsh-fakedev
--- a/hasher/hsh-fakedev
+++ b/hasher/hsh-fakedev
@@ -57,7 +57,7 @@ opt_check_dev()
 	local value
 	value="$(readlink -ev -- "$2")" &&
 		[ -b "$value" -o -c "$value" -o -p "$value" ] ||
-		Fatal "$1: $2: device not available."
+		fatal "$1: $2: device not available."
 	printf %s "$value"
 }
 
@@ -131,7 +131,7 @@ if [ -z "$reference" ]; then
 	name="$1" && shift
 	name="${name#/dev/}"
 	[ -n "${name##*/*}" -a -n "${name##*.*}" ] ||
-		Fatal "$name: invalid device file name"
+		fatal "$name: invalid device file name"
 
 	type="$1" && shift
 	case "$type" in
@@ -140,11 +140,11 @@ if [ -z "$reference" ]; then
 
 			major="$1" && shift
 			[ "$major" -gt 0 ] 2>/dev/null ||
-				Fatal "$major: invalid device file major number"
+				fatal "$major: invalid device file major number"
 
 			minor="$1" && shift
 			[ "$minor" -ge 0 ] 2>/dev/null ||
-				Fatal "$minor: invalid device file minor number"
+				fatal "$minor: invalid device file minor number"
 			;;
 		p)
 			[ "$#" -eq 0 ] || show_usage 'Too many arguments.'
@@ -152,7 +152,7 @@ if [ -z "$reference" ]; then
 			minor=
 			;;
 		*)
-			Fatal "$type: invalid device file type"
+			fatal "$type: invalid device file type"
 			;;
 	esac
 else
@@ -165,12 +165,12 @@ else
 		*\ special\ file|*\ fifo)
 			;;
 		*)
-			Fatal "$reference: unrecognized file type: $TEMP"
+			fatal "$reference: unrecognized file type: $TEMP"
 			;;
 	esac
 	eval set -- "$TEMP"
 	[ "$#" -ge 6 ] ||
-		Fatal "$reference: unrecognized file type: $TEMP"
+		fatal "$reference: unrecognized file type: $TEMP"
 
 	[ -n "$mode" ] || mode="$1"
 	shift
@@ -183,17 +183,17 @@ else
 
 	major="$1" && shift
 	[ "$major" -ge 0 ] 2>/dev/null ||
-		Fatal "$major: invalid device file major number"
+		fatal "$major: invalid device file major number"
 
 	minor="$1" && shift
 	[ "$minor" -ge 0 ] 2>/dev/null ||
-		Fatal "$minor: invalid device file minor number"
+		fatal "$minor: invalid device file minor number"
 
 	case "$1" in
 		block) type=b;;
 		character) type=c;;
 		fifo) type=p; major=; minor=;;
-		*) Fatal "$reference: unrecognized file type: $1";;
+		*) fatal "$reference: unrecognized file type: $1";;
 	esac
 	shift
 
@@ -201,12 +201,12 @@ else
 fi
 
 lock_workdir
-[ -d "$chroot" ] || Fatal "$chroot: cannot find chroot."
+[ -d "$chroot" ] || fatal "$chroot: cannot find chroot."
 [ -f "$chroot/.fakedata" ] ||
-	Fatal "$chroot: chroot was not created using --save-fakeroot option."
+	fatal "$chroot: chroot was not created using --save-fakeroot option."
 dev_name="$chroot/dev/$name"
 [ ! -e "$dev_name" ] ||
-	Fatal "$dev_name: File exists."
+	fatal "$dev_name: File exists."
 
 deduce_lock_hasher_priv
 
@@ -224,7 +224,7 @@ __EOF__
 tmp_inode="$(hsh-run --no-lock --root ${number:+--number="$number"} \
 	     ${hasher_priv_dir:+--hasher-priv-dir="$hasher_priv_dir"} \
 	     --execute="$chroot/.host/fakedev" -- "$workdir")" ||
-	Fatal 'Fake device creation failed.'
+	fatal 'Fake device creation failed.'
 
 touch "$dev_name"
 dev_inode="$(stat -c %i -- "$dev_name")"
@@ -239,5 +239,5 @@ chmod 755 "$entry"
 
 wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short \
     chrootuid1 </dev/null &&
-	Verbose 'Fake device creation complete.' ||
-	Fatal 'Fake device creation failed.'
+	verbose 'Fake device creation complete.' ||
+	fatal 'Fake device creation failed.'
diff --git a/hasher/hsh-initroot b/hasher/hsh-initroot
--- a/hasher/hsh-initroot
+++ b/hasher/hsh-initroot
@@ -115,7 +115,7 @@ while :; do
 		--no-wait-lock) lock_nowait=1
 			;;
 		--contents-index-*)
-			Info "Warning: obsolete option $1 ignored."
+			message "Warning: obsolete option $1 ignored."
 			shift
 			;;
 		--) shift; break
@@ -143,8 +143,8 @@ else
 fi
 
 lock_workdir
-[ -d "$chroot" ] || Fatal "$chroot: cannot access chroot."
-[ -d "$aptbox" ] || Fatal "$aptbox: cannot access aptbox."
+[ -d "$chroot" ] || fatal "$chroot: cannot access chroot."
+[ -d "$aptbox" ] || fatal "$aptbox: cannot access aptbox."
 deduce_lock_hasher_priv
 
 [ -z "$save_fakeroot" ] || init_list="$init_list cpio"
@@ -160,12 +160,12 @@ uid0="$(id -u)"
 gid0="$(id -g)"
 
 ugid1="$("$getugid1" ${number:+-$number})" ||
-	Fatal 'getugid1 failed.'
+	fatal 'getugid1 failed.'
 uid1="$(printf %s "$ugid1" |cut -d: -f1)"
 gid1="$(printf %s "$ugid1" |cut -d: -f2)"
 
 ugid2="$("$getugid2" ${number:+-$number})" ||
-	Fatal 'getugid2 failed.'
+	fatal 'getugid2 failed.'
 uid2="$(printf %s "$ugid2" |cut -d: -f1)"
 gid2="$(printf %s "$ugid2" |cut -d: -f2)"
 
@@ -176,13 +176,13 @@ check_tty
 
 init_list=`printf %s "$init_list" |LC_ALL=C tr -s ',[:space:]' ' ' |sed -e 's/^ \+//;s/ \+$//'`
 [ -n "$init_list" ] ||
-	Fatal 'Initial package file list is empty, cannot setup chroot.'
+	fatal 'Initial package file list is empty, cannot setup chroot.'
 
 initlist="$(print_uris $init_list)" ||
-	Fatal 'Failed to generate initial package file list.'
+	fatal 'Failed to generate initial package file list.'
 [ -n "$initlist" ] &&
-	Verbose 'Generated initial package file list.' ||
-	Fatal 'Failed to generate non-empty initial package file list; check your sources.list'
+	verbose 'Generated initial package file list.' ||
+	fatal 'Failed to generate non-empty initial package file list; check your sources.list'
 
 # reorder to get setup and filesystem first.
 initlist="$(printf %s "$initlist" |LC_ALL=C grep '/setup[-_]' ||:)
@@ -193,7 +193,7 @@ initlist="$(printf %s "$initlist" |LC_ALL=C grep -v '^$' ||:)"
 build_list=`printf %s "$build_list" |LC_ALL=C tr -s ',[:space:]' ' ' |sed -e 's/^ \+//;s/ \+$//'`
 if [ -n "$build_list" ]; then
 	buildlist="$(print_uris $build_list)" ||
-		Fatal 'Failed to generate build package file list.'
+		fatal 'Failed to generate build package file list.'
 	buildlist="$(
 		printf %s\\n "$buildlist" |while read bp; do
 			[ -n "$bp" ] || continue
@@ -202,10 +202,10 @@ if [ -n "$build_list" ]; then
 	)"
 	buildlist="$(printf %s "$buildlist" |LC_ALL=C grep -v '^$' ||:)"
 	[ -n "$buildlist" ] &&
-		Verbose 'Generated build package file list.' ||
-		Fatal 'Failed to generate non-empty build package file list; check your sources.list'
+		verbose 'Generated build package file list.' ||
+		fatal 'Failed to generate non-empty build package file list; check your sources.list'
 else
-	Verbose 'Package file list for build is empty, bypassing.'
+	verbose 'Package file list for build is empty, bypassing.'
 	buildlist=
 fi # $build_list
 
@@ -233,17 +233,17 @@ rmdir $verbose /proc /sys
 __EOF__
 	wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short \
 	    chrootuid1 </dev/null &&
-		Verbose "Removed old mount points." ||
-		Fatal "Failed to remove old mount points."
+		verbose "Removed old mount points." ||
+		fatal "Failed to remove old mount points."
 else
 	rmdir $verbose chroot/proc chroot/sys &&
-		Verbose "Removed old mount points." ||
-		Fatal "Failed to remove old mount points."
+		verbose "Removed old mount points." ||
+		fatal "Failed to remove old mount points."
 fi
 mkdir -m755 $verbose chroot/proc chroot/sys &&
 chgrp "$gid1" $verbose chroot/proc chroot/sys &&
-	Verbose 'Prepared mount points.' ||
-	Fatal 'Failed to prepare mount points.'
+	verbose 'Prepared mount points.' ||
+	fatal 'Failed to prepare mount points.'
 if [ -n "$save_fakeroot" ]; then
 	create_entry_fakeroot_header
 	cat >>"$entry" <<__EOF__
@@ -251,8 +251,8 @@ chgrp $verbose proc /proc
 __EOF__
 	wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short \
 	    chrootuid1 </dev/null &&
-		Verbose 'Updated faked /proc permissions.' ||
-		Fatal 'Failed to update faked /proc permissions.'
+		verbose 'Updated faked /proc permissions.' ||
+		fatal 'Failed to update faked /proc permissions.'
 fi
 
 . hsh-sh-cache-contents-functions
@@ -268,7 +268,7 @@ fi
 if [ -n "$build_list" ]; then
 	# Create /dev/log.
 	/usr/bin/mksock -m666 "$chroot/dev/log" ||
-		Fatal "Failed to create \`$chroot/dev/log' socket."
+		fatal "Failed to create \`$chroot/dev/log' socket."
 
 	# Create RPM build directory tree.
 	create_entry_header
@@ -294,8 +294,8 @@ __EOF__
 
 	wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short wlimit_bytes_written=$wlimit_bytes_out \
 	    chrootuid2 </dev/null &&
-		Verbose "Created RPM build directory tree." ||
-		Fatal 'Failed to create RPM build directory tree.'
+		verbose "Created RPM build directory tree." ||
+		fatal 'Failed to create RPM build directory tree.'
 fi # $build_list
 
 purge_chroot_in
diff --git a/hasher/hsh-install b/hasher/hsh-install
--- a/hasher/hsh-install
+++ b/hasher/hsh-install
@@ -65,7 +65,7 @@ while :; do
 			number="$(opt_check_number "$1" "$2")"
 			shift
 			;;
-		--save-fakeroot) Info "Warning: obsolete option $1 ignored."
+		--save-fakeroot) message "Warning: obsolete option $1 ignored."
 			;;
 		--wait-lock) lock_nowait=
 			;;
@@ -98,13 +98,13 @@ fi
 [ "$#" -ge 1 ] || show_usage 'Insufficient arguments.'
 
 lock_workdir
-[ -d "$chroot" ] || Fatal "$chroot: cannot find chroot."
-[ -d "$aptbox" ] || Fatal "$aptbox: cannot find aptbox."
+[ -d "$chroot" ] || fatal "$chroot: cannot find chroot."
+[ -d "$aptbox" ] || fatal "$aptbox: cannot find aptbox."
 
 filelist="$(print_uris "$@")" ||
-	Fatal 'Failed to generate package file list.'
+	fatal 'Failed to generate package file list.'
 if [ -z "$filelist" ]; then
-	Verbose 'Nothing to install.'
+	verbose 'Nothing to install.'
 	exit 0
 fi
 
@@ -149,8 +149,8 @@ __EOF__
 
 wlimit_time_elapsed=$wlimit_time_long wlimit_time_idle=$wlimit_time_long \
     chrootuid1 </dev/null &&
-	Verbose 'Packages installation complete.' ||
-	Fatal 'Packages installation failed.'
+	verbose 'Packages installation complete.' ||
+	fatal 'Packages installation failed.'
 
 purge_chroot_in
 update_RPM_database $filelist
diff --git a/hasher/hsh-rebuild b/hasher/hsh-rebuild
--- a/hasher/hsh-rebuild
+++ b/hasher/hsh-rebuild
@@ -123,11 +123,11 @@ while :; do
 			;;
 		--source-only) source_only=1
 			;;
-		--save-fakeroot) Info "Warning: obsolete option $1 ignored."
+		--save-fakeroot) message "Warning: obsolete option $1 ignored."
 			;;
 		--target) shift; target="$1"
 			[ -z "${target##[A-Za-z]*}" ] ||
-				Fatal "--target: $target: invalid architecture."
+				fatal "--target: $target: invalid architecture."
 			;;
 		--wait-lock) lock_nowait=
 			;;
@@ -173,7 +173,7 @@ sname="${source##*/}"
 shift
 
 lock_workdir
-[ -d "$chroot" ] || Fatal "$chroot: cannot find chroot."
+[ -d "$chroot" ] || fatal "$chroot: cannot find chroot."
 deduce_lock_hasher_priv
 
 # Create rebuild script.
@@ -187,7 +187,7 @@ export -n target ||:
 exec time rpmbuild --rebuild --target="\$target" $nodeps $rpmargs "\$@"
 __EOF__
 	chmod 755 "chroot/.host/rebuild"
-	Verbose 'Created rebuild script.'
+	verbose 'Created rebuild script.'
 fi
 
 . hsh-sh-rebuild-functions
@@ -243,8 +243,8 @@ __EOF__
 
 	deps="$(wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short wlimit_bytes_written=$wlimit_bytes_out \
 		    chrootuid2 </dev/null)" &&
-		Verbose "$sname: fetched installed file dependencies." ||
-		Fatal "$sname: failed to fetch installed file dependencies."
+		verbose "$sname: fetched installed file dependencies." ||
+		fatal "$sname: failed to fetch installed file dependencies."
 	calculate_required_mountpoints "$deps"
 fi
 
@@ -261,7 +261,7 @@ run_sisyphus_check '/.out' "$no_sisyphus_check_out" gpg
 case `find chroot/.out/ -mindepth 1 -maxdepth 1 -type f -name \*.src.rpm |LC_ALL=C grep -c '\.src\.rpm$'` in
 	0) subdir=.in ;;
 	1) subdir=.out ;;
-	*) Fatal 'Too many src.rpm files written.' ;;
+	*) fatal 'Too many src.rpm files written.' ;;
 esac
 
 make_repo
diff --git a/hasher/hsh-sh-cache-chroot-functions b/hasher/hsh-sh-cache-chroot-functions
--- a/hasher/hsh-sh-cache-chroot-functions
+++ b/hasher/hsh-sh-cache-chroot-functions
@@ -33,8 +33,8 @@ archive_chroot_cache()
 
 	# rpmdb
 	tar -cf "$rpmdb_archive" -C aptbox/var/lib/rpm/ . &&
-		Verbose 'RPM database archivation complete.' ||
-		Fatal 'RPM database archivation failed.'
+		verbose 'RPM database archivation complete.' ||
+		fatal 'RPM database archivation failed.'
 
 	# chroot
 	create_entry_fakeroot_header
@@ -47,8 +47,8 @@ __EOF__
 
 	wlimit_time_elapsed=$wlimit_time_long wlimit_time_idle=$wlimit_time_long \
 	    chrootuid1 </dev/null >"$chroot_archive" &&
-		Verbose 'Chroot archivation complete.' ||
-		Fatal 'Chroot archivation failed.'
+		verbose 'Chroot archivation complete.' ||
+		fatal 'Chroot archivation failed.'
 
 	trap - EXIT HUP INT QUIT TERM
 
@@ -77,33 +77,33 @@ check_chroot_cache()
 				#break
 			fi
 		done
-	[ ! -f "$bad" ] || Fatal 'Failed to check chroot cache.'
+	[ ! -f "$bad" ] || fatal 'Failed to check chroot cache.'
 
 	printf %s "$save_fakeroot" >"$cache_dir/chroot/fakeroot-options.new"
 
 	while :; do
 		for f in "$cache_dir"/chroot/{rpmdb.tar,chroot.cpio}; do
 			if [ ! -s "$f" ]; then
-				Verbose "Missing $f archive, invalidating chroot cache."
+				verbose "Missing $f archive, invalidating chroot cache."
 				rebuild_chroot_cache=1
 				break 2
 			fi
 		done
 
 		if ! cmp -s "$cache_dir"/chroot/fakeroot-options{.new,}; then
-			Verbose 'Fakeroot options changed, invalidating chroot cache.'
+			verbose 'Fakeroot options changed, invalidating chroot cache.'
 			rebuild_chroot_cache=1
 			break
 		fi
 
 		if ! cmp -s "$cache_dir"/chroot/list{.new,}/init; then
-			Verbose 'Init list changed, invalidating chroot cache.'
+			verbose 'Init list changed, invalidating chroot cache.'
 			rebuild_chroot_cache=1
 			break
 		fi
 
 		if ! cmp -s "$cache_dir"/chroot/list{.new,}/build; then
-			Verbose 'Build list changed, invalidating chroot cache.'
+			verbose 'Build list changed, invalidating chroot cache.'
 			rebuild_chroot_cache=1
 			break
 		fi
@@ -114,7 +114,7 @@ check_chroot_cache()
 				n="${f##*/}"
 				if [ "$cache_dir/chroot/package.new/$n" -nt "$cache_dir/chroot/package/$n" -o \
 				     "$cache_dir/chroot/package.new/$n" -ot "$cache_dir/chroot/package/$n" ]; then
-					Verbose "package $n changed, invalidating chroot cache"
+					verbose "package $n changed, invalidating chroot cache"
 					printf %s\\n "$n" >"$bad"
 					break
 				fi
@@ -135,20 +135,20 @@ unpack_chroot_cache()
 	f="$cache_dir/chroot/rpmdb.tar"
 	find aptbox/var/lib/rpm/ -mindepth 1 -depth -delete
 	tar -xf "$f" -C aptbox/var/lib/rpm/ &&
-		Verbose "Unpacked $f." ||
-		Fatal "Unpack of $f failed."
+		verbose "Unpacked $f." ||
+		fatal "Unpack of $f failed."
 
 	# chroot
 	f="$cache_dir/chroot/chroot.cpio"
 	wlimit_time_elapsed=$wlimit_time_long wlimit_time_idle=$wlimit_time_long \
 	    chrootuid1 /.host/cpio --extract --make-directories --sparse --quiet <"$f" &&
-		Verbose "Unpacked $f." ||
-		Fatal "Unpack of $f failed."
+		verbose "Unpacked $f." ||
+		fatal "Unpack of $f failed."
 	if [ -n "$save_fakeroot" ]; then
 		wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short \
 		    chrootuid1 /bin/touch /.fakedata </dev/null &&
-			Verbose "Created fakedata." ||
-			Fatal "Failed to create fakedata."
+			verbose "Created fakedata." ||
+			fatal "Failed to create fakedata."
 		create_entry_fakeroot_header
 		cat >>"$entry" <<__EOF__
 cd /
@@ -156,8 +156,8 @@ cpio --extract --make-directories --sparse --quiet --unconditional --preserve-mo
 __EOF__
 		wlimit_time_elapsed=$wlimit_time_long wlimit_time_idle=$wlimit_time_long \
 		    chrootuid1 <"$f" &&
-			Verbose "Unpacked $f for fakedata." ||
-			Fatal "Unpack of $f for fakedata failed."
+			verbose "Unpacked $f for fakedata." ||
+			fatal "Unpack of $f for fakedata failed."
 	fi
 	create_entry_fakeroot_header
 	cat >>"$entry" <<__EOF__
@@ -176,8 +176,8 @@ __EOF__
 
 	wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short wlimit_bytes_written=$wlimit_bytes_out \
 	    chrootuid1 </dev/null &&
-		Verbose 'First time initialization complete.' ||
-		Fatal 'First time initialization failed.'
+		verbose 'First time initialization complete.' ||
+		fatal 'First time initialization failed.'
 } # unpack_chroot_cache
 
 create_chroot()
@@ -188,15 +188,15 @@ create_chroot()
 	for f in $initlist; do
 		rpm2cpio "$f" |wlimit_time_elapsed=$wlimit_time_long wlimit_time_idle=$wlimit_time_long \
 		    chrootuid1 /.host/cpio --extract --make-directories --sparse --quiet &&
-			Verbose "Unpacked ${f##*/}." ||
-			Fatal "Unpack of ${f##*/} failed."
+			verbose "Unpacked ${f##*/}." ||
+			fatal "Unpack of ${f##*/} failed."
 	done
-	Verbose 'Unpacked initial package list.'
+	verbose 'Unpacked initial package list.'
 	if [ -n "$save_fakeroot" ]; then
 		wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short \
 		    chrootuid1 /bin/touch /.fakedata </dev/null &&
-			Verbose "Created fakedata." ||
-			Fatal "Failed to create fakedata."
+			verbose "Created fakedata." ||
+			fatal "Failed to create fakedata."
 		create_entry_fakeroot_header
 		cat >>"$entry" <<__EOF__
 cd /
@@ -205,8 +205,8 @@ __EOF__
 		for f in $initlist; do
 			rpm2cpio "$f" |wlimit_time_elapsed=$wlimit_time_long wlimit_time_idle=$wlimit_time_long \
 			    chrootuid1 &&
-				Verbose "Unpacked ${f##*/} for fakedata." ||
-				Fatal "Unpack of ${f##*/} for fakedata failed."
+				verbose "Unpacked ${f##*/} for fakedata." ||
+				fatal "Unpack of ${f##*/} for fakedata failed."
 		done
 	fi
 
@@ -224,12 +224,12 @@ echo '%_install_langs ${install_langs:-$def_install_langs}' >>/etc/rpm/macros
 # /WORKAROUND
 rpmdb --initdb
 __EOF__
-	Verbose "Created entry point: $entry"
+	verbose "Created entry point: $entry"
 
 	wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short wlimit_bytes_written=$wlimit_bytes_out \
 	    chrootuid1 </dev/null &&
-		Verbose 'Created RPM database.' ||
-		Fatal 'Failed to create RPM database.'
+		verbose 'Created RPM database.' ||
+		fatal 'Failed to create RPM database.'
 
 	create_entry_fakeroot_header
 	cat >>"$entry" <<__EOF__
@@ -240,8 +240,8 @@ __EOF__
 
 	wlimit_time_elapsed=$wlimit_time_long wlimit_time_idle=$wlimit_time_short \
 	    chrootuid1 </dev/null &&
-		Verbose 'Installed initial package list.' ||
-		Fatal 'Failed to install initial package list.'
+		verbose 'Installed initial package list.' ||
+		fatal 'Failed to install initial package list.'
 
 	purge_chroot_in
 	update_RPM_database --nodeps $initlist
@@ -254,8 +254,8 @@ cat >$f
 __EOF__
 			wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short wlimit_bytes_written=$wlimit_bytes_out \
 			    chrootuid1 <"$f" &&
-				Verbose "Installed $f file." ||
-				Fatal "Failed to install $f file."
+				verbose "Installed $f file." ||
+				fatal "Failed to install $f file."
 		fi
 	done
 
@@ -295,8 +295,8 @@ __EOF__
 
 		wlimit_time_elapsed=$wlimit_time_long wlimit_time_idle=$wlimit_time_short \
 		    chrootuid1 </dev/null &&
-			Verbose 'Installed build package list.' ||
-			Fatal 'Failed to install build package list.'
+			verbose 'Installed build package list.' ||
+			fatal 'Failed to install build package list.'
 
 		purge_chroot_in
 		update_RPM_database $buildlist
@@ -320,8 +320,8 @@ __EOF__
 
 		wlimit_time_elapsed=$wlimit_time_short wlimit_time_idle=$wlimit_time_short wlimit_bytes_written=$wlimit_bytes_out \
 		    chrootuid1 </dev/null &&
-			Verbose 'First time initialization complete.' ||
-			Fatal 'First time initialization failed.'
+			verbose 'First time initialization complete.' ||
+			fatal 'First time initialization failed.'
 	fi # $buildlist
 
 	archive_chroot_cache
diff --git a/hasher/hsh-sh-functions.in b/hasher/hsh-sh-functions.in
--- a/hasher/hsh-sh-functions.in
+++ b/hasher/hsh-sh-functions.in
@@ -28,30 +28,14 @@ PROG="${0##*/}"
 . shell-quote
 . shell-args
 
-Info()
-{
-	printf %s\\n "${0##*/}: $*" >&2
-}
-
-Fatal()
-{
-	Info "$@"
-	exit 1
-}
+quiet=
+verbose=
 
 # Create Var_of_$1 variable and set it to $2 if exist, otherwise to $1
 Helpify() # var_name=var_value [cmdline_key_name]
 {
 	eval "Var_of_${1%%=*}='
                                     (\$${2:-${1%%=*}})'"
-}
-
-quiet=
-verbose=
-Verbose()
-{
-	[ -n "$verbose" ] || return 0
-	printf %s\\n "${0##*/}: $*" >&2
 }
 
 print_version()
@@ -71,7 +55,7 @@ EOF
 
 show_usage()
 {
-	[ -z "$*" ] || Info "$*"
+	[ -z "$*" ] || message "$*"
 	echo "Try \`$PROG --help' for more information." >&2
 	exit 1
 }
@@ -267,7 +251,7 @@ opt_check_read()
 	[ -r "$2" ] &&
 		value="$(readlink -ev -- "$2")" &&
 		[ -r "$value" ] ||
-		Fatal "$1: $2: file not available."
+		fatal "$1: $2: file not available."
 	printf %s "$value"
 }
 
@@ -277,7 +261,7 @@ opt_check_dir()
 	[ -d "$2" -a -x "$2" ] &&
 		value="$(readlink -ev -- "$2")" &&
 		[ -d "$value" -a -x "$value" ] ||
-		Fatal "$1: $2: directory not available."
+		fatal "$1: $2: directory not available."
 	printf %s "$value"
 }
 
@@ -285,7 +269,7 @@ opt_check_number()
 {
 	[ -n "${2##0*}" -a -n "${2##*[!0-9]*}" ] &&
 		[ "$2" -gt 0 ] 2>/dev/null ||
-		Fatal "$1: $2: invalid number."
+		fatal "$1: $2: invalid number."
 	printf %s "$2"
 }
 
@@ -300,7 +284,7 @@ parse_common_options()
 			;;
 		-V|--version) print_version "$PROG"
 			;;
-		*) Fatal "Unrecognized option: $1"
+		*) fatal "Unrecognized option: $1"
 			;;
 	esac
 }
@@ -313,13 +297,13 @@ set_workdir()
 	workdir="$(/bin/pwd)" || return 1
 
 	[ -n "$(printf %s "$workdir" |tr -d /.)" ] ||
-		Fatal "$workdir: illegal working directory."
+		fatal "$workdir: illegal working directory."
 	if printf %s "$workdir" |LC_ALL=C grep -qs '[`"$\]'; then
-		Fatal "$workdir: illegal symbols in pathname."
+		fatal "$workdir: illegal symbols in pathname."
 	fi
-	[ -w . ] || Fatal "$workdir: unwritable working directory."
+	[ -w . ] || fatal "$workdir: unwritable working directory."
 
-	Verbose "changed working directory to \`$workdir'"
+	verbose "changed working directory to \`$workdir'"
 	aptbox="$workdir/aptbox"
 	chroot="$workdir/chroot"
 	cache_dir="${cache_dir:-$workdir/cache}"
@@ -334,7 +318,7 @@ install_static_helper()
 	local dst="${2:-$name}"
 	local path="$(type -p "$src")"
 	[ -n "$path" -a -z "${path##/*}" ] ||
-		Fatal "Static helper $src not found."
+		fatal "Static helper $src not found."
 	install -p -m755 $verbose "$path" "$chroot/.host/$dst"
 }
 
@@ -362,13 +346,13 @@ read_apt_config()
 
 	name="$orig_name"
 	get_apt_config "$name" value
-	[ -n "$value" ] || Fatal "apt-config: undefined: $name"
+	[ -n "$value" ] || fatal "apt-config: undefined: $name"
 
 	while [ -n "${value##/*}" ]; do
 		dir_name="${name%::*}"
 		[ "$dir_name" != "$name" ] || break
 		get_apt_config "$dir_name" dir_value
-		[ -n "$dir_value" ] || Fatal "apt-config: undefined: $dir_name"
+		[ -n "$dir_value" ] || fatal "apt-config: undefined: $dir_name"
 		name="$dir_name"
 		value="$dir_value$value"
 	done
@@ -400,31 +384,31 @@ check_helpers()
 	[ -z "$check_helpers_done" ] || return 0
 
 	[ -d "${hasher_priv_dir:-$def_hasher_priv_dir}" ] ||
-		Fatal "${hasher_priv_dir:-$def_hasher_priv_dir}: cannot access hasher-priv helper directory."
+		fatal "${hasher_priv_dir:-$def_hasher_priv_dir}: cannot access hasher-priv helper directory."
 
 	getconf="${hasher_priv_dir:-$def_hasher_priv_dir}/getconf.sh"
 	[ -x "$getconf" ] ||
-		Fatal "$getconf: cannot access getconf helper."
+		fatal "$getconf: cannot access getconf helper."
 
 	getugid1="${hasher_priv_dir:-$def_hasher_priv_dir}/getugid1.sh"
 	[ -x "$getugid1" ] ||
-		Fatal "$getugid1: cannot access getugid1 helper."
+		fatal "$getugid1: cannot access getugid1 helper."
 
 	getugid2="${hasher_priv_dir:-$def_hasher_priv_dir}/getugid2.sh"
 	[ -x "$getugid2" ] ||
-		Fatal "$getugid2: cannot access getugid2 helper."
+		fatal "$getugid2: cannot access getugid2 helper."
 
 	chrootuid1="${hasher_priv_dir:-$def_hasher_priv_dir}/chrootuid1.sh"
 	[ -x "$chrootuid1" ] ||
-		Fatal "$chrootuid1: cannot access chrootuid1 helper."
+		fatal "$chrootuid1: cannot access chrootuid1 helper."
 
 	chrootuid2="${hasher_priv_dir:-$def_hasher_priv_dir}/chrootuid2.sh"
 	[ -x "$chrootuid2" ] ||
-		Fatal "$chrootuid2: cannot access chrootuid2 helper."
+		fatal "$chrootuid2: cannot access chrootuid2 helper."
 
 	makedev="${hasher_priv_dir:-$def_hasher_priv_dir}/makedev.sh"
 	[ -x "$makedev" ] ||
-		Fatal "$makedev: cannot access makedev helper."
+		fatal "$makedev: cannot access makedev helper."
 
 	check_helpers_done=1
 }
@@ -446,7 +430,7 @@ copy_chroot_incoming()
 {
 	purge_chroot_in
 	install -p -m644 $verbose -- "$@" chroot/.in/ ||
-		Fatal 'failed to copy files.'
+		fatal 'failed to copy files.'
 }
 
 # assumed: cwd == workdir
@@ -463,16 +447,16 @@ update_repo()
 {
 	[ -z "$no_stuff" ] || return 0
 	"$aptbox/genbasedir" --topdir=${repo:-$def_repo} --no-oldhashfile --bz2only --mapi ${target:-$def_target} hasher &&
-		Verbose 'updated hasher repository indices.' ||
-		Fatal 'failed to update hasher repository indices.'
+		verbose 'updated hasher repository indices.' ||
+		fatal 'failed to update hasher repository indices.'
 }
 
 # assumed: defined variables: hash
 update_RPM_database()
 {
 	rpmi -i $verbose $hash --dbpath "$aptbox/var/lib/rpm" $exclude_docs --ignorearch --ignoresize --noorder --noscripts --notriggers --justdb "$@"
-		Verbose 'RPM database updated.' ||
-		Fatal 'RPM database update failed.'
+		verbose 'RPM database updated.' ||
+		fatal 'RPM database update failed.'
 }
 
 # execute as pseudoroot.
@@ -533,7 +517,7 @@ lock_workdir()
 	enable -f /usr/lib/bash/lockf lockf
 	if builtin lockf -n "$workdir"; then
 		echo $$ >"$workdir/pid"
-		Verbose "Locked working directory \`$workdir'"
+		verbose "Locked working directory \`$workdir'"
 		return 0
 	fi
 
@@ -542,23 +526,23 @@ lock_workdir()
 	   pid="$(head -c32 -- "$workdir/pid")" &&
 	   [ "$pid" -gt 0 ] 2>/dev/null; then
 		if kill -0 -- "$pid" 2>/dev/null; then
-			Info "working directory \`$workdir' is already locked by pid=$pid."
+			message "working directory \`$workdir' is already locked by pid=$pid."
 			ps hp "$pid" >&2
 		else
-			Info "working directory \`$workdir' is already locked by stale pid=$pid."
+			message "working directory \`$workdir' is already locked by stale pid=$pid."
 		fi
 	fi
 
 	if [ -z "$lock_nowait" ]; then
-		Verbose "Waiting for working directory lock..."
+		verbose "Waiting for working directory lock..."
 		if builtin lockf "$workdir"; then
 			echo $$ >"$workdir/pid"
-			Verbose "Locked working directory \`$workdir'"
+			verbose "Locked working directory \`$workdir'"
 			return 0
 		fi
 	fi
 
-	Fatal "Unable to lock working directory \`$workdir'"
+	fatal "Unable to lock working directory \`$workdir'"
 }
 
 # assumed: variables initialized by check_helpers()
@@ -569,18 +553,18 @@ lock_hasher_config()
 
 	local file
 	file="$("$getconf" ${number:+-$number})" ||
-		Fatal 'hasher-priv getconf failed.'
+		fatal 'hasher-priv getconf failed.'
 
 	enable -f /usr/lib/bash/lockf lockf
 	local lock_param=
 	[ -z "$lock_nowait" ] || lock_param=-n
-	Verbose "Acquiring lock for config file \`$file'..."
+	verbose "Acquiring lock for config file \`$file'..."
 	if builtin lockf $lock_param "$file"; then
 		config_is_locked=1
-		Verbose "Locked config file \`$file'"
+		verbose "Locked config file \`$file'"
 		return 0
 	else
-		Verbose "Config file \`$file' is busy"
+		verbose "Config file \`$file' is busy"
 		return 1
 	fi
 }
@@ -644,15 +628,15 @@ deduce_number_from_directory()
 	local gid
 
 	[ -d "$dir" ] ||
-		Fatal "$dir: Directory not available."
+		fatal "$dir: Directory not available."
 
 	# take gid from directory ownership
 	gid="$(find "$dir" -maxdepth 0 -type d -printf '%G')"
 	[ "$gid" -ge 0 ] 2>/dev/null ||
-		Fatal "$dir: Failed to get directory ownership."
+		fatal "$dir: Failed to get directory ownership."
 
 	iterate_config_files_set_number '' is_config_matches_gid "$gid" ||
-		Fatal 'Failed to deduce hasher config number from directory ownership.'
+		fatal 'Failed to deduce hasher config number from directory ownership.'
 }
 
 deduce_lock_hasher_priv()
@@ -661,7 +645,7 @@ deduce_lock_hasher_priv()
 	check_helpers
 	deduce_number_from_directory "$dir"
 	lock_hasher_config ||
-		Fatal 'Failed to lock hasher-priv'
+		fatal 'Failed to lock hasher-priv'
 }
 
 allocate_lock_hasher_priv()
@@ -672,7 +656,7 @@ allocate_lock_hasher_priv()
 	# if subconfig is already defined, just use it
 	if [ -n "$number" ]; then
 		lock_hasher_config ||
-			Fatal 'Failed to lock hasher-priv'
+			fatal 'Failed to lock hasher-priv'
 		return 0
 	fi
 
@@ -689,7 +673,7 @@ allocate_lock_hasher_priv()
 
 		# if all configs are busy and lock_nowait was set, bail out
 		[ -z "$saved_lock_nowait" ] ||
-			Fatal 'Failed to lock hasher-priv'
+			fatal 'Failed to lock hasher-priv'
 
 		# wait for next iteration
 		n="$(($n+1))"
@@ -705,7 +689,7 @@ print_uris()
 	local out
 	if ! out="$("$aptbox/apt-get" -q -y --print-uris install -- "$@" 2>&1)"; then
 		printf %s\\n "$out" >&2
-		Fatal 'failed to calculate package file list.'
+		fatal 'failed to calculate package file list.'
 	fi
 
 	local all_pattern="'\\([a-z]\\+\\):\\([^']\\+\\)' .*"
@@ -714,26 +698,26 @@ print_uris()
 	local all_uris
 	if ! all_uris="$(printf %s "$out" |sed -ne "s/^$all_pattern/\\2/pg")"; then
 		printf %s\\n "$out" >&2
-		Fatal 'failed to filter package file list.'
+		fatal 'failed to filter package file list.'
 	fi
 
 	local local_uris cached_uris=
 	if ! local_uris="$(printf %s "$out" |sed -ne "s/^$local_pattern/\\2/pg")"; then
 		printf %s\\n "$out" >&2
-		Fatal 'failed to filter package file list.'
+		fatal 'failed to filter package file list.'
 	fi
 
 	if [ "$all_uris" != "$local_uris" ]; then
 		if [ -z "$APT_Get_PrintLocalFile" ]; then
 			if ! out="$("$aptbox/apt-get" -o APT::Get::PrintLocalFile=yes -q -y --print-uris install -- "$@" 2>&1)"; then
 				printf %s\\n "$out" >&2
-				Fatal 'calculated package file list is not local and apt-get does not support APT::Get::PrintLocalFile option.'
+				fatal 'calculated package file list is not local and apt-get does not support APT::Get::PrintLocalFile option.'
 			fi
 
 			if ! cached_uris="$(printf %s "$out" |sed -ne "s/^$all_pattern/\\2/pg")" ||
 			   [ -n "$cached_uris" ]; then
 				printf %s\\n "$out" >&2
-				Fatal 'calculated package file list is not local and apt-get does not support APT::Get::PrintLocalFile option.'
+				fatal 'calculated package file list is not local and apt-get does not support APT::Get::PrintLocalFile option.'
 			fi
 
 			APT_Get_PrintLocalFile=1
@@ -741,22 +725,22 @@ print_uris()
 
 		if [ -n "$verbose" ]; then
 			"$aptbox/apt-get" -y -d install -- "$@" >&2 ||
-				Fatal 'failed to download packages from calculated package file list.'
+				fatal 'failed to download packages from calculated package file list.'
 		else
 			if ! out="$("$aptbox/apt-get" -y -d install -- "$@" 2>&1)"; then
 				printf %s\\n "$out" >&2
-				Fatal 'failed to download packages from calculated package file list.'
+				fatal 'failed to download packages from calculated package file list.'
 			fi
 		fi
 
 		if ! out="$("$aptbox/apt-get" -o APT::Get::PrintLocalFile=yes -q -y --print-uris install -- "$@" 2>&1)"; then
 			printf %s\\n "$out" >&2
-			Fatal 'failed to calculate local package file list.'
+			fatal 'failed to calculate local package file list.'
 		fi
 
 		if ! cached_uris="$(printf %s "$out" |LC_ALL=C grep ^/)" || [ -z "$cached_uris" ]; then
 			printf %s\\n "$out" >&2
-			Fatal 'failed to calculate local package file list.'
+			fatal 'failed to calculate local package file list.'
 		fi
 	fi
 
@@ -766,7 +750,7 @@ $cached_uris" || local_uris="$cached_uris"
 	fi
 
 	printf %s "$local_uris" &&
-		Verbose 'calculated package file list.'
+		verbose 'calculated package file list.'
 }
 
 parse_xauth_entry()
@@ -777,7 +761,7 @@ parse_xauth_entry()
 
 	if [ -z "$XAUTH_DISPLAY" -o -n "${XAUTH_DISPLAY##*:*}" \
 	  -o -z "$XAUTH_PROTO" -o -z "$XAUTH_KEY" ]; then
-		Info "Invalid auth entry for DISPLAY \`$DISPLAY', disabling X11 forwarding."
+		message "Invalid auth entry for DISPLAY \`$DISPLAY', disabling X11 forwarding."
 		return 1
 	fi
 
@@ -790,12 +774,12 @@ prepare_x11_forwarding()
 	[ -n "$x11_forwarding" ] || return 0
 
 	if [ -z "$DISPLAY" ]; then
-		Info 'DISPLAY not set, disabling X11 forwarding.'
+		message 'DISPLAY not set, disabling X11 forwarding.'
 		return 1
 	fi
 
 	if [ -n "${DISPLAY##*:*}" ]; then
-		Info 'Invalid DISPLAY set, disabling X11 forwarding.'
+		message 'Invalid DISPLAY set, disabling X11 forwarding.'
 		return 1
 	fi
 
@@ -816,7 +800,7 @@ prepare_x11_forwarding()
 			{ rm -f "$xfile"; return 1; }
 		rm -f "$xfile"
 	else
-		Fatal 'Invalid $x11_forwarding value.'
+		fatal 'Invalid $x11_forwarding value.'
 	fi
 
 	parse_xauth_entry $xentry || return 1
diff --git a/hasher/mkaptbox b/hasher/mkaptbox
--- a/hasher/mkaptbox
+++ b/hasher/mkaptbox
@@ -89,7 +89,7 @@ while :; do
 			;;
 		--target) shift; target="$1"
 			[ -z "${target##[A-Za-z]*}" ] ||
-				Fatal "--target: $target: invalid architecture."
+				fatal "--target: $target: invalid architecture."
 			;;
 		-u|--update) update=1
 			;;
@@ -134,8 +134,8 @@ repo="$(readlink -ef -- "$repo")"
 
 # does aptbox exist yet?
 if [ -e aptbox -o -L aptbox ]; then
-	[ -n "$force" ] || Fatal "remove $aptbox first."
-	[ -d aptbox ] || Fatal "$aptbox: invalid pathname."
+	[ -n "$force" ] || fatal "remove $aptbox first."
+	[ -d aptbox ] || fatal "$aptbox: invalid pathname."
 
 	# empty dir?
 	if rmdir -- aptbox 2>/dev/null; then
@@ -144,14 +144,14 @@ if [ -e aptbox -o -L aptbox ]; then
 	else
 		cd aptbox
 		[ -d ./etc/apt -a -d ./var/lib/rpm ] ||
-			Fatal "$aptbox: doesn't look valid."
+			fatal "$aptbox: doesn't look valid."
 	fi
 else
 	mkdir -m700 $verbose -- aptbox
 	cd aptbox
 fi
 
-Verbose "Changed working directory to \`$aptbox'."
+verbose "Changed working directory to \`$aptbox'."
 
 # create apt/rpm skeleton directories.
 mkdir -p $verbose -- \
@@ -171,10 +171,10 @@ if [ -z "$apt_prefix" ]; then
 	apt_libdir="$LD_LIBRARY_PATH"
 else
 	[ -d "$apt_prefix" ] ||
-		Fatal "$apt_prefix: directory not available."
+		fatal "$apt_prefix: directory not available."
 
 	if printf %s "$apt_prefix" |LC_ALL=C grep -qs '[`"$\]'; then
-		Fatal "$apt_prefix: illegal symbols in apt prefix."
+		fatal "$apt_prefix: illegal symbols in apt prefix."
 	fi
 
 	slibdir="$(getconf SLIB ||:)"
@@ -182,7 +182,7 @@ else
 
 	apt_libdir="$apt_prefix/$slibdir"
 	[ -d "$apt_libdir" ] ||
-		Fatal "$apt_libdir: directory not available."
+		fatal "$apt_libdir: directory not available."
 
 	if [ -n "$LD_LIBRARY_PATH" ]; then
 		apt_libdir="$LD_LIBRARY_PATH:$apt_libdir"
@@ -191,13 +191,13 @@ else
 	for n in apt-cache apt-config apt-get genbasedir; do
 		prog="$apt_prefix/bin/$n"
 		[ -x "$prog" ] ||
-			Fatal "$prog: program not available."
+			fatal "$prog: program not available."
 		var="$(printf 'prog_%s' "$n" |tr - _)"
 		eval "$var=\"$(quote_arg "$prog")\""
 	done
 fi
 if printf %s "$apt_libdir" |LC_ALL=C grep -qs '[`"$\]'; then
-	Fatal "$LD_LIBRARY_PATH: illegal symbols in LD_LIBRARY_PATH."
+	fatal "$LD_LIBRARY_PATH: illegal symbols in LD_LIBRARY_PATH."
 fi
 
 # create aptbox version of ~/.rpmrc if necessary.
@@ -231,7 +231,7 @@ APT_CONFIG="$apt_config_file" \
 ${aptbox_home:+HOME="$aptbox_home"} \
 exec $setarch $(eval printf %s "$(printf '$prog_%s' "$n" |tr - _)") "\$@"
 __EOF__
-	Verbose "created $n wrapper"
+	verbose "created $n wrapper"
 	chmod $verbose a+x "$n"
 done
 
@@ -240,7 +240,7 @@ cat >regenbasedir <<__EOF__
 "$aptbox/genbasedir" --topdir="$repo" --no-oldhashfile --bz2only --mapi ${target:-$def_target} hasher "\$@"
 "$aptbox/apt-get" ${quiet:+-qq} update
 __EOF__
-Verbose "created regenbasedir"
+verbose "created regenbasedir"
 chmod $verbose a+x regenbasedir
 
 # create initial apt.conf file.
@@ -251,7 +251,7 @@ __EOF__
 read_apt_config Dir::Etc::SourceList sl_value
 [ -z "${sl_value##/*}" ] &&
 	[ -r "$sl_value" -a -s "$sl_value" ] ||
-	Fatal "apt-config: broken Dir::Etc::SourceList: $sl_value"
+	fatal "apt-config: broken Dir::Etc::SourceList: $sl_value"
 
 # if cdroms.list is not empty, copy it and apt indices into aptbox
 read_apt_config Dir::State::cdroms cd_value
@@ -276,7 +276,7 @@ RPM::RootDir "$aptbox";
 APT::Install::Virtual "true";
 APT::Install::VirtualVersion "true";
 __EOF__
-Verbose "Created APT configuration file \`$apt_config_file'."
+verbose "Created APT configuration file \`$apt_config_file'."
 
 # create a new sources.list file.
 target_config="./etc/apt/sources.list"
@@ -284,11 +284,11 @@ cat >"$target_config" <<__EOF__
 ${no_stuff:+#}rpm file:$repo ${target:-$def_target} hasher
 $(LC_ALL=C grep '^[^#]' "$sl_value")
 __EOF__
-Verbose "Created APT source list file \`$target_config'."
+verbose "Created APT source list file \`$target_config'."
 
 # create a new rpm database.
 rpmdb --initdb --dbpath "$aptbox/var/lib/rpm"
-Verbose "Created RPM database in \`./var/lib/rpm/'."
+verbose "Created RPM database in \`./var/lib/rpm/'."
 
 cd "$workdir"
 update_repo
